global_defs {
    router_id RTR-1
}

vrrp_script chk_isp {
    script "ping -c 1 -W 2 10.100.0.5 > /dev/null 2>&1"
    interval 2
    weight -20
}

vrrp_instance VI_10 {
    state MASTER
    interface vlan10
    virtual_router_id 10
    priority 115
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass vlan10
    }
    virtual_ipaddress {
        172.16.10.254/24
    }
    track_script {
        chk_isp
    }
}

vrrp_instance VI_20 {
    state BACKUP
    interface vlan20
    virtual_router_id 20
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass vlan20
    }
    virtual_ipaddress {
        172.16.21.254/23
    }
    track_script {
        chk_isp
    }
}

vrrp_instance VI_30 {
    state MASTER
    interface vlan30
    virtual_router_id 30
    priority 115
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass vlan30
    }
    virtual_ipaddress {
        172.16.30.62/26
    }
    track_script {
        chk_isp
    }
}
